name: deployment-pipeline
run-name: Pipeline | ${{ github.event.head_commit.message }} | By @${{ github.actor }}
on:
  push:
    branches:
      - master

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TERRAFORM_STATE_BUCKET: ${{ vars.TERRAFORM_STATE_BUCKET }}
  AWS_STS_EXTERNAL_KEY: ${{ secrets.AWS_STS_EXTERNAL_KEY }}
  AWS_TERRAFORM_ROLE_ARN: ${{ vars.AWS_TERRAFORM_ROLE_ARN }}

jobs:

  run-test-discord-interaction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
          python -m pip install ./bot/commons
          python -m pip install ./bot/discord_interaction_lambda_function
      - name: Run request verification tests
        run: python -m unittest bot/discord_interaction_lambda_function/test/test_verify.py
      - name: Run Discord interaction lambda tests
        run: python -m unittest bot/discord_interaction_lambda_function/test/test_discord_interaction_lambda.py

  run-tests-commons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
          python -m pip install ./bot/commons
          python -m pip install ./bot/discord_interaction_lambda_function
      - name: Run user DynamoDB table tests
        run: python -m unittest bot/commons/test/test_gw2_user_repo.py
      - name: Run guild DynamoDB table tests
        run: python -m unittest bot/commons/test/test_gw2_guild_repo.py

  package-common-layer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Package common layer
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt --target python
          echo "Installed all dependencies in 'python' directory"
          mkdir python/bot
          cp -r bot/commons python/bot/commons
          zip -r common_layer.zip python
          echo "Zipped common layer into archive 'common_layer.zip'"
          stat common_layer.zip
      - uses: actions/upload-artifact@v3
        with:
          name: common-layer-deployment-package
          path: common_layer.zip
    needs: [run-test-discord-interaction, run-tests-commons]

  package-discord-interaction-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Package discord interaction lambda
        run: zip -r discord_interaction_lambda.zip bot/discord_interaction_lambda_function/* -x bot/discord_interaction_lambda_function/test*
      - uses: actions/upload-artifact@v3
        with:
          name: discord-interaction-lambda-package
          path: discord_interaction_lambda.zip
    needs: [run-test-discord-interaction, run-tests-commons]

  package-scheduled-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Package scheduled lambda
        run: zip -r scheduled_lambda.zip bot/scheduled_lambda_function/* -x bot/scheduled_lambda_function/test*
      - uses: actions/upload-artifact@v3
        with:
          name: scheduled-lambda-package
          path: scheduled_lambda.zip
    needs: [ run-test-discord-interaction, run-tests-commons ]

  package-command-lambdas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare packages folder
        run: mkdir command_lambda_packages
      - name: Package help command lambda
        run: zip -r command_lambda_packages/help_lambda.zip bot/help_command/*
      - name: Package api key add lambda
        run: zip -r command_lambda_packages/api_key_lambda.zip bot/api_key_command/*
      - name: Package home world lambda
        run: zip -r command_lambda_packages/home_world_lambda.zip bot/home_world_command/*
      - name: Package manager role lambda
        run: zip -r command_lambda_packages/manager_role_lambda.zip bot/manager_role_command/*
      - name: Package wvw role lambda
        run: zip -r command_lambda_packages/wvw_role_lambda.zip bot/wvw_role_command/*
      - name: Package wvw rank lambda
        run: zip -r command_lambda_packages/wvw_rank_lambda.zip bot/wvw_rank_command/*
      - name: Package wvw matchup lambda
        run: zip -r command_lambda_packages/wvw_matchup_lambda.zip bot/wvw_matchup_command/*
      - name: Package next wvw matchup lambda
        run: zip -r command_lambda_packages/next_wvw_matchup_lambda.zip bot/next_wvw_matchup_command/*
      - name: Package next announcement channel lambda
        run: zip -r command_lambda_packages/announcement_channel_lambda.zip bot/announcement_channel_command/*
      - name: Package wvw raid lambda
        run: zip -r command_lambda_packages/wvw_raid_lambda.zip bot/wvw_raid_command/*
      - name: Package wvw daily lambda
        run: zip -r command_lambda_packages/wvw_daily_lambda.zip bot/wvw_daily_command/*
      - name: Package wvw weekly lambda
        run: zip -r command_lambda_packages/wvw_weekly_lambda.zip bot/wvw_weekly_command/*
      - name: Package currencies lambda
        run: zip -r command_lambda_packages/wvw_currencies_lambda.zip bot/wvw_currencies_command/*
      - name: Package items lambda
        run: zip -r command_lambda_packages/wvw_items_lambda.zip bot/wvw_items_command/*
      - name: Package legendaries lambda
        run: zip -r command_lambda_packages/wvw_legendaries_lambda.zip bot/wvw_legendaries_command/*
      - name: Package guild language lambda
        run: zip -r command_lambda_packages/guild_language_lambda.zip bot/guild_language_command/*
      - uses: actions/upload-artifact@v3
        with:
          name: command-lambda-packages
          path: command_lambda_packages/
    needs: [run-test-discord-interaction, run-tests-commons]

  terraform-validate:
    environment: staging # does not matter technically
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT_NAME }}
      TERRAFORM_STATE_FILE: ${{ vars.TERRAFORM_STATE_FILE }}
      DISCORD_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      APPLICATION_ID: ${{ vars.APPLICATION_ID }}
      APPLICATION_PUBLIC_KEY: ${{ vars.APPLICATION_PUBLIC_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - uses: hashicorp/setup-terraform@v2
      - name: Validate Terraform configuration
        run: |
          cd terraform
          terraform init -backend-config="bucket=$TERRAFORM_STATE_BUCKET" -backend-config="key=$TERRAFORM_STATE_FILE" -backend-config="region=$AWS_REGION"
          terraform validate
    needs: [
      package-common-layer, package-discord-interaction-lambda, package-scheduled-lambda, package-command-lambdas]

  terraform-plan-stg:
    environment: staging
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT_NAME }}
      TERRAFORM_STATE_FILE: ${{ vars.TERRAFORM_STATE_FILE }}
      DISCORD_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      DISCORD_APP_NAME: ${{ vars.DISCORD_APPLICATION_NAME }}
      APPLICATION_ID: ${{ vars.APPLICATION_ID }}
      APPLICATION_PUBLIC_KEY: ${{ vars.APPLICATION_PUBLIC_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - uses: actions/download-artifact@v3
      - name: Plan actions by Terraform
        run: |
          cd terraform
          terraform init -backend-config="bucket=$TERRAFORM_STATE_BUCKET" -backend-config="key=$TERRAFORM_STATE_FILE" -backend-config="region=$AWS_REGION"
          terraform plan -out=app.tfplan -var-file=inputs.tfvars \
            -var aws_region="$AWS_REGION" \
            -var environment="$ENVIRONMENT" \
            -var discord_bot_token="$DISCORD_BOT_TOKEN" \
            -var aws_key_id="$AWS_ACCESS_KEY_ID" \
            -var aws_secret_key="$AWS_SECRET_ACCESS_KEY" \
            -var aws_terraform_role_arn="$AWS_TERRAFORM_ROLE_ARN" \
            -var aws_assume_role_external_id="$AWS_STS_EXTERNAL_KEY" \
            -var discord_application_id="$APPLICATION_ID" \
            -var discord_application_public_key="$APPLICATION_PUBLIC_KEY" \
            -var discord_application_name="$DISCORD_APP_NAME"
          cd ..
      - uses: actions/upload-artifact@v3
        with:
          name: terraform-plan-stg
          path: terraform/app.tfplan
    needs: [terraform-validate]

  terraform-apply-stg:
    runs-on: ubuntu-latest
    environment: staging
    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT_NAME }}
      TERRAFORM_STATE_FILE: ${{ vars.TERRAFORM_STATE_FILE }}
      DISCORD_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      DISCORD_APP_NAME: ${{ vars.DISCORD_APPLICATION_NAME }}
      APPLICATION_ID: ${{ vars.APPLICATION_ID }}
      APPLICATION_PUBLIC_KEY: ${{ vars.APPLICATION_PUBLIC_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - uses: actions/download-artifact@v3
      - name: Apply Terraform plan
        run: |
          cd terraform
          terraform init -backend-config="bucket=$TERRAFORM_STATE_BUCKET" -backend-config="key=$TERRAFORM_STATE_FILE" -backend-config="region=$AWS_REGION"
          terraform apply -auto-approve "./../terraform-plan-stg/app.tfplan"
    needs: terraform-plan-stg

  terraform-destroy-stg:
    runs-on: ubuntu-latest
    environment: staging_destroy
    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT_NAME }}
      TERRAFORM_STATE_FILE: ${{ vars.TERRAFORM_STATE_FILE }}
      DISCORD_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      DISCORD_APP_NAME: ${{ vars.DISCORD_APPLICATION_NAME }}
      APPLICATION_ID: ${{ vars.APPLICATION_ID }}
      APPLICATION_PUBLIC_KEY: ${{ vars.APPLICATION_PUBLIC_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - uses: actions/download-artifact@v3
      - name: Destroy infrastructure with Terraform
        run: |
          cd terraform
          terraform init -backend-config="bucket=$TERRAFORM_STATE_BUCKET" -backend-config="key=$TERRAFORM_STATE_FILE" -backend-config="region=$AWS_REGION"
          terraform destroy -var-file=inputs.tfvars \
            -var aws_region="$AWS_REGION" \
            -var environment="$ENVIRONMENT" \
            -var discord_bot_token="$DISCORD_BOT_TOKEN" \
            -var aws_key_id="$AWS_ACCESS_KEY_ID" \
            -var aws_secret_key="$AWS_SECRET_ACCESS_KEY" \
            -var aws_terraform_role_arn="$AWS_TERRAFORM_ROLE_ARN" \
            -var aws_assume_role_external_id="$AWS_STS_EXTERNAL_KEY" \
            -var discord_application_id="$APPLICATION_ID" \
            -var discord_application_public_key="$APPLICATION_PUBLIC_KEY" \
            -var discord_application_name="$DISCORD_APP_NAME"
    needs: terraform-plan-stg

  register-commands-test-guild:
    environment: staging
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT_NAME }}
      DISCORD_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      APPLICATION_ID: ${{ vars.APPLICATION_ID }}
      APPLICATION_PUBLIC_KEY: ${{ vars.APPLICATION_PUBLIC_KEY }}
      GUILD_ID: ${{ vars.DISCORD_TEST_GUILD_ID }}
      COMMAND_TYPE: GUILD
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install script dependencies
        run: python -m pip install -r requirements.txt
      - name: Register commands to test guilds
        run: python commands/register_slash_commands.py
    needs: terraform-apply-stg

  announce-release-stg:
    environment: staging
    runs-on: ubuntu-latest
    env:
      ANNOUNCEMENT_FUNCTION_ARN: ${{ vars.ANNOUNCEMENT_FUNCTION_ARN }}
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
    steps: # AWS CLI is pre-installed to GitHub actions images
      - name: Invoke announcement lambda function
        run: |
          aws lambda invoke --function-name "$ANNOUNCEMENT_FUNCTION_ARN" --invocation-type Event \
            --cli-binary-format raw-in-base64-out \
            --payload '{"lambda_wvw_event_type":"release","commit_message":"${{ env.COMMIT_MESSAGE }}"}' response.json
    needs: terraform-apply-stg

  terraform-plan-prd:
    environment: production
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT_NAME }}
      TERRAFORM_STATE_FILE: ${{ vars.TERRAFORM_STATE_FILE }}
      DISCORD_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      DISCORD_APP_NAME: ${{ vars.DISCORD_APPLICATION_NAME }}
      APPLICATION_ID: ${{ vars.APPLICATION_ID }}
      APPLICATION_PUBLIC_KEY: ${{ vars.APPLICATION_PUBLIC_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - uses: actions/download-artifact@v3
      - name: Plan actions by Terraform
        run: |
          cd terraform
          terraform init -backend-config="bucket=$TERRAFORM_STATE_BUCKET" -backend-config="key=$TERRAFORM_STATE_FILE" -backend-config="region=$AWS_REGION"
          terraform plan -out=app.tfplan -var-file=inputs.tfvars \
            -var aws_region="$AWS_REGION" \
            -var environment="$ENVIRONMENT" \
            -var discord_bot_token="$DISCORD_BOT_TOKEN" \
            -var aws_key_id="$AWS_ACCESS_KEY_ID" \
            -var aws_secret_key="$AWS_SECRET_ACCESS_KEY" \
            -var aws_terraform_role_arn="$AWS_TERRAFORM_ROLE_ARN" \
            -var aws_assume_role_external_id="$AWS_STS_EXTERNAL_KEY" \
            -var discord_application_id="$APPLICATION_ID" \
            -var discord_application_public_key="$APPLICATION_PUBLIC_KEY" \
            -var discord_application_name="$DISCORD_APP_NAME"
          cd ..
      - uses: actions/upload-artifact@v3
        with:
          name: terraform-plan-prd
          path: terraform/app.tfplan
    needs: terraform-apply-stg

  terraform-apply-prd:
    runs-on: ubuntu-latest
    environment: production
    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT_NAME }}
      TERRAFORM_STATE_FILE: ${{ vars.TERRAFORM_STATE_FILE }}
      DISCORD_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      DISCORD_APP_NAME: ${{ vars.DISCORD_APPLICATION_NAME }}
      APPLICATION_ID: ${{ vars.APPLICATION_ID }}
      APPLICATION_PUBLIC_KEY: ${{ vars.APPLICATION_PUBLIC_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - uses: actions/download-artifact@v3
      - name: Apply Terraform plan
        run: |
          cd terraform
          terraform init -backend-config="bucket=$TERRAFORM_STATE_BUCKET" -backend-config="key=$TERRAFORM_STATE_FILE" -backend-config="region=$AWS_REGION"
          terraform apply -auto-approve "./../terraform-plan-prd/app.tfplan"
    needs: terraform-plan-prd

  terraform-destroy-prd:
    runs-on: ubuntu-latest
    environment: production-destroy
    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT_NAME }}
      TERRAFORM_STATE_FILE: ${{ vars.TERRAFORM_STATE_FILE }}
      DISCORD_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      DISCORD_APP_NAME: ${{ vars.DISCORD_APPLICATION_NAME }}
      APPLICATION_ID: ${{ vars.APPLICATION_ID }}
      APPLICATION_PUBLIC_KEY: ${{ vars.APPLICATION_PUBLIC_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - uses: actions/download-artifact@v3
      - name: Destroy infrastructure with Terraform
        run: |
          cd terraform
          terraform init -backend-config="bucket=$TERRAFORM_STATE_BUCKET" -backend-config="key=$TERRAFORM_STATE_FILE" -backend-config="region=$AWS_REGION"
          terraform destroy -var-file=inputs.tfvars \
            -var aws_region="$AWS_REGION" \
            -var environment="$ENVIRONMENT" \
            -var discord_bot_token="$DISCORD_BOT_TOKEN" \
            -var aws_key_id="$AWS_ACCESS_KEY_ID" \
            -var aws_secret_key="$AWS_SECRET_ACCESS_KEY" \
            -var aws_terraform_role_arn="$AWS_TERRAFORM_ROLE_ARN" \
            -var aws_assume_role_external_id="$AWS_STS_EXTERNAL_KEY" \
            -var discord_application_id="$APPLICATION_ID" \
            -var discord_application_public_key="$APPLICATION_PUBLIC_KEY" \
            -var discord_application_name="$DISCORD_APP_NAME"
    needs: terraform-plan-prd

  register-commands-global:
    runs-on: ubuntu-latest
    environment: production
    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT_NAME }}
      DISCORD_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      APPLICATION_ID: ${{ vars.APPLICATION_ID }}
      APPLICATION_PUBLIC_KEY: ${{ vars.APPLICATION_PUBLIC_KEY }}
      COMMAND_TYPE: GLOBAL
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install script dependencies
        run: python -m pip install -r requirements.txt
      - name: Register commands globally
        run: python commands/register_slash_commands.py
    needs: terraform-apply-prd

  announce-release-prd:
    environment: production
    runs-on: ubuntu-latest
    env:
      ANNOUNCEMENT_FUNCTION_ARN: ${{ vars.ANNOUNCEMENT_FUNCTION_ARN }}
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
    steps: # AWS CLI is pre-installed to GitHub actions images
      - name: Invoke announcement lambda function
        run: |
          aws lambda invoke --function-name "$ANNOUNCEMENT_FUNCTION_ARN" --invocation-type Event \
            --cli-binary-format raw-in-base64-out \
            --payload '{"lambda_wvw_event_type":"release","commit_message":"${{ env.COMMIT_MESSAGE }}"}' response.json
    needs: terraform-apply-prd

